name: 'Setup Node.js'
description: 'Setup Node.js, cache and install dependencies. Requires checkout to be run first.'

inputs:
  node-version:
    description: 'Node.js version to use'
    required: false
    default: '22.22.0'
  reader-token:
    description: 'GitHub token for npm registry authentication'
    required: true

runs:
  using: 'composite'
  steps:
    - name: Install pnpm
      uses: pnpm/action-setup@fc06bc1257f339d1d5d8b3a19a8cae5388b55320 # v4.4.0

    - name: Use Node.js v${{ inputs.node-version }}
      uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020 # v4.4.0
      with:
        node-version: ${{ inputs.node-version }}
        registry-url: 'https://npm.pkg.github.com'
        cache: 'pnpm'
        token: ${{ inputs.reader-token }}

    - name: Install dependencies
      shell: bash
      run: pnpm install --frozen-lockfile
      env:
        NODE_AUTH_TOKEN: ${{ inputs.reader-token }}
