name: 'Run E2E tests'
description: 'Run Playwright E2E tests for a specific app'

inputs:
  app:
    description: 'The app to run E2E tests for (e.g., intern, ekstern)'
    required: true
  working-directory:
    description: 'Working directory for the app'
    required: false
    default: ''

runs:
  using: 'composite'
  steps:
    - name: Install Playwright browsers
      shell: bash
      run: pnpm exec playwright install --with-deps chromium

    - name: Run E2E tests
      shell: bash
      run: pnpm --filter ${{ inputs.app }} test:e2e

    - name: Upload Playwright report
      uses: actions/upload-artifact@v4
      if: failure()
      with:
        name: playwright-report-${{ inputs.app }}
        path: apps/${{ inputs.app }}/playwright-report
        retention-days: 7
