/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
	'/api/v9/alderspensjon/simulering': {
		parameters: {
			query?: never
			header?: never
			path?: never
			cookie?: never
		}
		get?: never
		put?: never
		/**
		 * Simuler alderspensjon
		 * @description Lag en prognose for framtidig alderspensjon med støtte for AFP i offentlig sektor. Feltet 'epsHarInntektOver2G' brukes til å angi hvorvidt ektefelle/partner/samboer har inntekt over 2 ganger grunnbeløpet. Dersom simulering med de angitte parametre resulterer i avslag i vilkårsprøvingen, vil responsen inneholde alternative parametre som vil gi et innvilget simuleringsresultat
		 */
		post: operations['simulerAlderspensjonV9']
		delete?: never
		options?: never
		head?: never
		patch?: never
		trace?: never
	}
	'/api/v3/tidligste-hel-uttaksalder': {
		parameters: {
			query?: never
			header?: never
			path?: never
			cookie?: never
		}
		get?: never
		put?: never
		/**
		 * Tidligst mulige uttaksalder ved helt uttak
		 * @description Finn tidligst mulige uttaksalder for innlogget bruker ved helt (100 %) uttak.
		 */
		post: operations['finnTidligsteHelUttaksalderV3']
		delete?: never
		options?: never
		head?: never
		patch?: never
		trace?: never
	}
	'/api/v3/pensjonsavtaler': {
		parameters: {
			query?: never
			header?: never
			path?: never
			cookie?: never
		}
		get?: never
		put?: never
		/**
		 * Hent pensjonsavtaler (versjon 3)
		 * @description Henter pensjonsavtalene til den innloggede/angitte brukeren. I request må verdi av 'maaneder' være 0..11.
		 */
		post: operations['fetchAvtalerV3']
		delete?: never
		options?: never
		head?: never
		patch?: never
		trace?: never
	}
	'/api/v2/simuler-oftp': {
		parameters: {
			query?: never
			header?: never
			path?: never
			cookie?: never
		}
		get?: never
		put?: never
		/**
		 * Simuler offentlig tjenestepensjon hos TP-leverandør bruker er medlem av
		 * @description Simulerer offentlig tjenestepensjon hos TP-leverandør som har ansvar for brukers tjenestepensjon
		 */
		post: operations['simulerOffentligTjenestepensjonV2']
		delete?: never
		options?: never
		head?: never
		patch?: never
		trace?: never
	}
	'/api/v2/simuler-oftp/foer-1963': {
		parameters: {
			query?: never
			header?: never
			path?: never
			cookie?: never
		}
		get?: never
		put?: never
		/**
		 * Simuler offentlig tjenestepensjon hos TP-leverandør bruker er medlem av
		 * @description Simulerer offentlig tjenestepensjon hos TP-leverandør som har ansvar for brukers tjenestepensjon
		 */
		post: operations['simulerOffentligTjenestepensjonFoer1963V1']
		delete?: never
		options?: never
		head?: never
		patch?: never
		trace?: never
	}
	'/api/v1/encrypt': {
		parameters: {
			query?: never
			header?: never
			path?: never
			cookie?: never
		}
		get?: never
		put?: never
		/**
		 * Krypter tekst
		 * @description Krypterer angitt tekst (typisk brukstilfelle er for fødselsnumre)
		 */
		post: operations['encrypt']
		delete?: never
		options?: never
		head?: never
		patch?: never
		trace?: never
	}
	'/api/v1/decrypt': {
		parameters: {
			query?: never
			header?: never
			path?: never
			cookie?: never
		}
		get?: never
		put?: never
		/**
		 * Dekrypter tekst
		 * @description Dekrypterer angitt tekst (typisk brukstilfelle er for fødselsnumre)
		 */
		post: operations['decrypt']
		delete?: never
		options?: never
		head?: never
		patch?: never
		trace?: never
	}
	'/api/v1/alderspensjon/anonym-simulering': {
		parameters: {
			query?: never
			header?: never
			path?: never
			cookie?: never
		}
		get?: never
		put?: never
		/**
		 * Simuler alderspensjon anonymt (ikke innlogget)
		 * @description Lag en prognose for framtidig alderspensjon med støtte for AFP i offentlig sektor. Feltet 'epsHarInntektOver2G' brukes til å angi hvorvidt ektefelle/partner/samboer har inntekt over 2 ganger grunnbeløpet. Dersom simulering med de angitte parametre resulterer i avslag i vilkårsprøvingen, vil responsen inneholde alternative parametre som vil gi et innvilget simuleringsresultat
		 */
		post: operations['simulerAnonymAlderspensjonV1']
		delete?: never
		options?: never
		head?: never
		patch?: never
		trace?: never
	}
	'/api/intern/v1/pensjon/simulering': {
		parameters: {
			query?: never
			header?: never
			path?: never
			cookie?: never
		}
		get?: never
		put?: never
		/**
		 * Simuler pensjon
		 * @description Lager en prognose for framtidig alderspensjon med støtte for AFP.
		 */
		post: operations['simulerPensjon']
		delete?: never
		options?: never
		head?: never
		patch?: never
		trace?: never
	}
	'/api/intern/v1/lagre-simulering': {
		parameters: {
			query?: never
			header?: never
			path?: never
			cookie?: never
		}
		get?: never
		put?: never
		/**
		 * Lagre simuleringsresultat
		 * @description Lagrer et simuleringsresultat via Skribenten-tjenesten.
		 */
		post: operations['lagreSimuleringV1']
		delete?: never
		options?: never
		head?: never
		patch?: never
		trace?: never
	}
	'/api/intern/v1/eps': {
		parameters: {
			query?: never
			header?: never
			path?: never
			cookie?: never
		}
		get?: never
		put?: never
		/**
		 * Hent nyligste EPS
		 * @description Henter informasjon om nyligste ektefelle/partner/samboer.
		 */
		post: operations['nyligsteEps']
		delete?: never
		options?: never
		head?: never
		patch?: never
		trace?: never
	}
	'/api/ekstern/v1/pensjon/simulering': {
		parameters: {
			query?: never
			header?: never
			path?: never
			cookie?: never
		}
		get?: never
		put?: never
		/**
		 * Simuler pensjon
		 * @description Lag en prognose for framtidig alderspensjon med støtte for AFP. Dersom simulering med de angitte parametre resulterer i avslag i vilkårsprøvingen, vil responsen inneholde alternative parametre som vil gi et innvilget simuleringsresultat
		 */
		post: operations['simulerPensjon_1']
		delete?: never
		options?: never
		head?: never
		patch?: never
		trace?: never
	}
	'/api/v7/person': {
		parameters: {
			query?: never
			header?: never
			path?: never
			cookie?: never
		}
		/**
		 * Hent personinformasjon
		 * @description Henter informasjon om personen hvis person-ID er angitt enten i bearer-tokenet eller som fnr-header.
		 */
		get: operations['person']
		put?: never
		post?: never
		delete?: never
		options?: never
		head?: never
		patch?: never
		trace?: never
	}
	'/api/v6/person': {
		parameters: {
			query?: never
			header?: never
			path?: never
			cookie?: never
		}
		/**
		 * Hent personinformasjon
		 * @description Henter informasjon om personen hvis person-ID er angitt enten i bearer-tokenet eller som fnr-header.
		 */
		get: operations['personV6']
		put?: never
		post?: never
		delete?: never
		options?: never
		head?: never
		patch?: never
		trace?: never
	}
	'/api/v4/vedtak/loepende-vedtak': {
		parameters: {
			query?: never
			header?: never
			path?: never
			cookie?: never
		}
		/**
		 * Har løpende vedtak
		 * @description Hvorvidt den innloggede brukeren har løpende uføretrygd med uttaksgrad, alderspensjon med uttaksgrad, AFP i privat eller offentlig sektor
		 */
		get: operations['hentLoependeVedtakV4']
		put?: never
		post?: never
		delete?: never
		options?: never
		head?: never
		patch?: never
		trace?: never
	}
	'/api/v3/tpo-livsvarig-offentlig-afp': {
		parameters: {
			query?: never
			header?: never
			path?: never
			cookie?: never
		}
		/**
		 * Hent løpende livsvarig offentlig AFP
		 * @description Henter detaljer om løpende livsvarig AFP i offentlig sektor for brukeren
		 */
		get: operations['hentLivsvarigOffentligAfpDetaljerV3']
		put?: never
		post?: never
		delete?: never
		options?: never
		head?: never
		patch?: never
		trace?: never
	}
	'/api/v2/tpo-livsvarig-offentlig-afp': {
		parameters: {
			query?: never
			header?: never
			path?: never
			cookie?: never
		}
		/**
		 * Hent løpende livsvarig offentlig AFP
		 * @description Henter detaljer om løpende livsvarig AFP i offentlig sektor for brukeren
		 */
		get: operations['hentLivsvarigOffentligAfpDetaljer']
		put?: never
		post?: never
		delete?: never
		options?: never
		head?: never
		patch?: never
		trace?: never
	}
	'/api/v2/ekskludert': {
		parameters: {
			query?: never
			header?: never
			path?: never
			cookie?: never
		}
		/**
		 * Om personen er ekskludert fra å bruke kalkulatoren
		 * @description Eksludering kan skyldes medlemskap i Apotekerforeningen
		 */
		get: operations['erEkskludertV2']
		put?: never
		post?: never
		delete?: never
		options?: never
		head?: never
		patch?: never
		trace?: never
	}
	'/api/v1/vedtak': {
		parameters: {
			query?: never
			header?: never
			path?: never
			cookie?: never
		}
		/**
		 * Hent vedtak
		 * @description Henter løpende vedtak om alderspensjon, AFP (i privat og offentlig sektor) og uføretrygd, samt fremtidige alderspensjonsvedtak
		 */
		get: operations['hentVedtak']
		put?: never
		post?: never
		delete?: never
		options?: never
		head?: never
		patch?: never
		trace?: never
	}
	'/api/v1/ufoeregrad': {
		parameters: {
			query?: never
			header?: never
			path?: never
			cookie?: never
		}
		/**
		 * Hente gjeldende uføregrad
		 * @description Hente gjeldende uføregrad fra løpende vedtak om uføretrygd om det finnes
		 */
		get: operations['hentUfoeregrad']
		put?: never
		post?: never
		delete?: never
		options?: never
		head?: never
		patch?: never
		trace?: never
	}
	'/api/v1/tpo-medlemskap': {
		parameters: {
			query?: never
			header?: never
			path?: never
			cookie?: never
		}
		/**
		 * Hent medlemskap i offentlige tjenestepensjonsordninger
		 * @description Henter både aktive og inaktive medlemskap til brukeren i offentlige tjenestepensjonsordninger
		 */
		get: operations['hentMedlemskapITjenestepensjonsordninger']
		put?: never
		post?: never
		delete?: never
		options?: never
		head?: never
		patch?: never
		trace?: never
	}
	'/api/v1/loepende-omstillingsstoenad-eller-gjenlevendeytelse': {
		parameters: {
			query?: never
			header?: never
			path?: never
			cookie?: never
		}
		/**
		 * Mottar omstillingsstønad eller gjenlevende ytelse
		 * @description Hvorvidt den innloggede brukeren mottar omstillingsstønad eller gjenlevende ytelse
		 */
		get: operations['mottarOmstillingsstoenadEllerGjenlevendeYtelse']
		put?: never
		post?: never
		delete?: never
		options?: never
		head?: never
		patch?: never
		trace?: never
	}
	'/api/v1/land-liste': {
		parameters: {
			query?: never
			header?: never
			path?: never
			cookie?: never
		}
		/**
		 * Hent land-liste
		 * @description Henter liste over land med navn og status som avtaleland. Denne tjenesten er åpen - krever ikke autentisering.
		 */
		get: operations['landListe']
		put?: never
		post?: never
		delete?: never
		options?: never
		head?: never
		patch?: never
		trace?: never
	}
	'/api/v1/er-apoteker': {
		parameters: {
			query?: never
			header?: never
			path?: never
			cookie?: never
		}
		/**
		 * Om personen er ekskludert fra å bruke kalkulatoren
		 * @description Eksludering skyldes medlemskap i Apotekerforeningen
		 */
		get: operations['erApotekerV1']
		put?: never
		post?: never
		delete?: never
		options?: never
		head?: never
		patch?: never
		trace?: never
	}
	'/api/v1/ekskludert': {
		parameters: {
			query?: never
			header?: never
			path?: never
			cookie?: never
		}
		/**
		 * Om personen er ekskludert fra å bruke kalkulatoren
		 * @description Eksludering kan skyldes løpende uføretrygd, gjenlevendeytelse eller medlemskap i Apotekerforeningen
		 */
		get: operations['erEkskludertV1']
		put?: never
		post?: never
		delete?: never
		options?: never
		head?: never
		patch?: never
		trace?: never
	}
	'/api/v1/ansatt-id': {
		parameters: {
			query?: never
			header?: never
			path?: never
			cookie?: never
		}
		/**
		 * Hent ansatt-ID
		 * @description Henter informasjon som identifiserer den innloggede ansatte.
		 */
		get: operations['ansattId']
		put?: never
		post?: never
		delete?: never
		options?: never
		head?: never
		patch?: never
		trace?: never
	}
	'/api/tpo-medlemskap': {
		parameters: {
			query?: never
			header?: never
			path?: never
			cookie?: never
		}
		/**
		 * Har offentlig tjenestepensjonsforhold
		 * @description Hvorvidt den innloggede brukeren har offentlig tjenestepensjonsforhold
		 */
		get: operations['harTjenestepensjonsforhold']
		put?: never
		post?: never
		delete?: never
		options?: never
		head?: never
		patch?: never
		trace?: never
	}
	'/api/status': {
		parameters: {
			query?: never
			header?: never
			path?: never
			cookie?: never
		}
		/**
		 * Sjekk status
		 * @description Hent status for applikasjonens helsetilstand
		 */
		get: operations['status']
		put?: never
		post?: never
		delete?: never
		options?: never
		head?: never
		patch?: never
		trace?: never
	}
	'/api/sak-status': {
		parameters: {
			query?: never
			header?: never
			path?: never
			cookie?: never
		}
		/**
		 * Har uføretrygd/gjenlevendeytelse
		 * @description Hvorvidt den innloggede brukeren har løpende uføretrygd eller gjenlevendeytelse
		 */
		get: operations['harRelevantSak']
		put?: never
		post?: never
		delete?: never
		options?: never
		head?: never
		patch?: never
		trace?: never
	}
	'/api/intern/v1/sivilstatus': {
		parameters: {
			query?: never
			header?: never
			path?: never
			cookie?: never
		}
		/**
		 * Hent nåværende sivilstatus
		 * @description Henter informasjon om nåværende sivilstatus.
		 */
		get: operations['naavaerendeSivilstatus']
		put?: never
		post?: never
		delete?: never
		options?: never
		head?: never
		patch?: never
		trace?: never
	}
	'/api/intern/v1/person': {
		parameters: {
			query?: never
			header?: never
			path?: never
			cookie?: never
		}
		/**
		 * Hent personinformasjon
		 * @description Henter informasjon om personen hvis person-ID er angitt som fnr-header.
		 */
		get: operations['personV1']
		put?: never
		post?: never
		delete?: never
		options?: never
		head?: never
		patch?: never
		trace?: never
	}
	'/api/inntekt': {
		parameters: {
			query?: never
			header?: never
			path?: never
			cookie?: never
		}
		/**
		 * Siste pensjonsgivende inntekt
		 * @description Henter den innloggede brukerens sist skattelignede pensjonsgivende inntekt
		 */
		get: operations['sistePensjonsgivendeInntekt']
		put?: never
		post?: never
		delete?: never
		options?: never
		head?: never
		patch?: never
		trace?: never
	}
	'/api/feature/{name}': {
		parameters: {
			query?: never
			header?: never
			path?: never
			cookie?: never
		}
		/**
		 * Hvorvidt en gitt funksjonsbryter er skrudd på
		 * @description Hent status for en gitt funksjonsbryter (hvorvidt funksjonen er skrudd på)
		 */
		get: operations['isEnabled']
		put?: never
		post?: never
		delete?: never
		options?: never
		head?: never
		patch?: never
		trace?: never
	}
}
export type webhooks = Record<string, never>
export interface components {
	schemas: {
		PersonligSimuleringAlderSpecV9: {
			/** Format: int32 */
			aar: number
			/** Format: int32 */
			maaneder: number
		}
		PersonligSimuleringGradertUttakSpecV9: {
			/** Format: int32 */
			grad: number
			uttaksalder: components['schemas']['PersonligSimuleringAlderSpecV9']
			/** Format: int32 */
			aarligInntektVsaPensjonBeloep?: number
		}
		PersonligSimuleringHeltUttakSpecV9: {
			uttaksalder: components['schemas']['PersonligSimuleringAlderSpecV9']
			aarligInntektVsaPensjon?: components['schemas']['PersonligSimuleringInntektSpecV9']
		}
		PersonligSimuleringInntektSpecV9: {
			/** Format: int32 */
			beloep: number
			sluttAlder: components['schemas']['PersonligSimuleringAlderSpecV9']
		}
		PersonligSimuleringInnvilgetLivsvarigOffentligAfpSpecV9: {
			/** Format: double */
			aarligBruttoBeloep: number
			/** Format: date */
			uttakFom: string
			/** Format: int32 */
			sistRegulertGrunnbeloep?: number
		}
		PersonligSimuleringSpecV9: {
			/** @enum {string} */
			simuleringstype:
				| 'ALDERSPENSJON'
				| 'PRE2025_OFFENTLIG_AFP_ETTERFULGT_AV_ALDERSPENSJON'
				| 'ALDERSPENSJON_MED_AFP_PRIVAT'
				| 'ALDERSPENSJON_MED_AFP_OFFENTLIG_LIVSVARIG'
				| 'ALDERSPENSJON_MED_GJENLEVENDERETT'
				| 'ENDRING_ALDERSPENSJON'
				| 'ENDRING_ALDERSPENSJON_MED_AFP_PRIVAT'
				| 'ENDRING_ALDERSPENSJON_MED_AFP_OFFENTLIG_LIVSVARIG'
				| 'ENDRING_ALDERSPENSJON_MED_GJENLEVENDERETT'
			/** Format: date */
			foedselsdato: string
			/** Format: int32 */
			aarligInntektFoerUttakBeloep?: number
			gradertUttak?: components['schemas']['PersonligSimuleringGradertUttakSpecV9']
			heltUttak: components['schemas']['PersonligSimuleringHeltUttakSpecV9']
			utenlandsperiodeListe?: components['schemas']['PersonligSimuleringUtenlandsperiodeSpecV9'][]
			/** @enum {string} */
			sivilstand?:
				| 'UNKNOWN'
				| 'UOPPGITT'
				| 'UGIFT'
				| 'GIFT'
				| 'ENKE_ELLER_ENKEMANN'
				| 'SKILT'
				| 'SEPARERT'
				| 'REGISTRERT_PARTNER'
				| 'SEPARERT_PARTNER'
				| 'SKILT_PARTNER'
				| 'GJENLEVENDE_PARTNER'
				| 'SAMBOER'
			epsHarInntektOver2G?: boolean
			epsHarPensjon?: boolean
			afpInntektMaanedFoerUttak?: boolean
			/** @enum {string} */
			afpOrdning?:
				| 'AFPKOM'
				| 'AFPSTAT'
				| 'FINANS'
				| 'KONV_K'
				| 'KONV_O'
				| 'LONHO'
				| 'NAVO'
			innvilgetLivsvarigOffentligAfp?: components['schemas']['PersonligSimuleringInnvilgetLivsvarigOffentligAfpSpecV9'][]
		}
		PersonligSimuleringUtenlandsperiodeSpecV9: {
			/** Format: date */
			fom: string
			/** Format: date */
			tom?: string
			landkode: string
			arbeidetUtenlands: boolean
		}
		PersonligSimuleringAarligInntektResultV9: {
			/** Format: int32 */
			aar: number
			/** Format: int32 */
			pensjonsgivendeInntektBeloep: number
		}
		PersonligSimuleringAarligPensjonResultV9: {
			/** Format: int32 */
			alder: number
			/** Format: int32 */
			beloep: number
			/** Format: int32 */
			maanedligBeloep?: number
		}
		PersonligSimuleringAfpPrivatResultV9: {
			/** Format: int32 */
			alder: number
			/** Format: int32 */
			beloep: number
			/** Format: int32 */
			kompensasjonstillegg: number
			/** Format: int32 */
			kronetillegg: number
			/** Format: int32 */
			livsvarig: number
			/** Format: int32 */
			maanedligBeloep?: number
		}
		PersonligSimuleringAlderResultV9: {
			/** Format: int32 */
			aar: number
			/** Format: int32 */
			maaneder: number
		}
		PersonligSimuleringAlderspensjonResultV9: {
			/** Format: int32 */
			alder: number
			/** Format: int32 */
			beloep: number
			/** Format: int32 */
			inntektspensjonBeloep?: number
			/** Format: int32 */
			garantipensjonBeloep?: number
			/** Format: double */
			delingstall?: number
			/** Format: int32 */
			pensjonBeholdningFoerUttakBeloep?: number
			/** Format: double */
			andelsbroekKap19?: number
			/** Format: double */
			andelsbroekKap20?: number
			/** Format: double */
			sluttpoengtall?: number
			/** Format: int32 */
			trygdetidKap19?: number
			/** Format: int32 */
			trygdetidKap20?: number
			/** Format: int32 */
			poengaarFoer92?: number
			/** Format: int32 */
			poengaarEtter91?: number
			/** Format: double */
			forholdstall?: number
			/** Format: int32 */
			grunnpensjon?: number
			/** Format: int32 */
			tilleggspensjon?: number
			/** Format: int32 */
			pensjonstillegg?: number
			/** Format: int32 */
			skjermingstillegg?: number
			/** Format: int32 */
			kapittel19Gjenlevendetillegg?: number
		}
		PersonligSimuleringAlternativResultV9: {
			gradertUttaksalder?: components['schemas']['PersonligSimuleringAlderResultV9']
			/** Format: int32 */
			uttaksgrad?: number
			heltUttaksalder: components['schemas']['PersonligSimuleringAlderResultV9']
		}
		PersonligSimuleringMaanedligPensjonResultV9: {
			/** Format: int32 */
			gradertUttakMaanedligBeloep?: number
			/** Format: int32 */
			heltUttakMaanedligBeloep: number
		}
		PersonligSimuleringPre2025OffentligAfpResultV9: {
			/** Format: int32 */
			alderAar: number
			/** Format: int32 */
			totaltAfpBeloep: number
			/** Format: int32 */
			tidligereArbeidsinntekt: number
			/** Format: int32 */
			grunnbeloep: number
			/** Format: double */
			sluttpoengtall: number
			/** Format: int32 */
			trygdetid: number
			/** Format: int32 */
			poengaarTom1991: number
			/** Format: int32 */
			poengaarFom1992: number
			/** Format: int32 */
			grunnpensjon: number
			/** Format: int32 */
			tilleggspensjon: number
			/** Format: int32 */
			afpTillegg: number
			/** Format: int32 */
			saertillegg: number
			/** Format: int32 */
			afpGrad: number
			afpAvkortetTil70Prosent: boolean
		}
		PersonligSimuleringResultV9: {
			alderspensjon: components['schemas']['PersonligSimuleringAlderspensjonResultV9'][]
			alderspensjonMaanedligVedEndring?: components['schemas']['PersonligSimuleringMaanedligPensjonResultV9']
			pre2025OffentligAfp?: components['schemas']['PersonligSimuleringPre2025OffentligAfpResultV9']
			afpPrivat?: components['schemas']['PersonligSimuleringAfpPrivatResultV9'][]
			afpOffentlig?: components['schemas']['PersonligSimuleringAarligPensjonResultV9'][]
			vilkaarsproeving: components['schemas']['PersonligSimuleringVilkaarsproevingResultV9']
			harForLiteTrygdetid?: boolean
			/** Format: int32 */
			trygdetid?: number
			opptjeningGrunnlagListe?: components['schemas']['PersonligSimuleringAarligInntektResultV9'][]
		}
		PersonligSimuleringVilkaarsproevingResultV9: {
			vilkaarErOppfylt: boolean
			alternativ?: components['schemas']['PersonligSimuleringAlternativResultV9']
		}
		PersonligSimuleringInnvilgetLivsvarigOffentligAfpSpecV3: {
			/** Format: double */
			aarligBruttoBeloep?: number
			/** Format: date */
			uttakFom?: string
			/** Format: int32 */
			sistRegulertGrunnbeloep?: number
		}
		UttaksalderAlderSpecV3: {
			/** Format: int32 */
			aar: number
			/** Format: int32 */
			maaneder: number
		}
		UttaksalderInntektSpecV3: {
			/** Format: int32 */
			beloep: number
			sluttAlder?: components['schemas']['UttaksalderAlderSpecV3']
		}
		UttaksalderSpecV3: {
			/** @enum {string} */
			simuleringstype?:
				| 'ALDERSPENSJON'
				| 'PRE2025_OFFENTLIG_AFP_ETTERFULGT_AV_ALDERSPENSJON'
				| 'ALDERSPENSJON_MED_AFP_PRIVAT'
				| 'ALDERSPENSJON_MED_AFP_OFFENTLIG_LIVSVARIG'
				| 'ALDERSPENSJON_MED_GJENLEVENDERETT'
				| 'ENDRING_ALDERSPENSJON'
				| 'ENDRING_ALDERSPENSJON_MED_AFP_PRIVAT'
				| 'ENDRING_ALDERSPENSJON_MED_AFP_OFFENTLIG_LIVSVARIG'
				| 'ENDRING_ALDERSPENSJON_MED_GJENLEVENDERETT'
			/** Format: int32 */
			aarligInntektFoerUttakBeloep?: number
			aarligInntektVsaPensjon?: components['schemas']['UttaksalderInntektSpecV3']
			utenlandsperiodeListe?: components['schemas']['UttaksalderUtenlandsperiodeSpecV3'][]
			/** @enum {string} */
			sivilstand?:
				| 'UNKNOWN'
				| 'UOPPGITT'
				| 'UGIFT'
				| 'GIFT'
				| 'ENKE_ELLER_ENKEMANN'
				| 'SKILT'
				| 'SEPARERT'
				| 'REGISTRERT_PARTNER'
				| 'SEPARERT_PARTNER'
				| 'SKILT_PARTNER'
				| 'GJENLEVENDE_PARTNER'
				| 'SAMBOER'
			epsHarInntektOver2G: boolean
			epsHarPensjon: boolean
			innvilgetLivsvarigOffentligAfp?: components['schemas']['PersonligSimuleringInnvilgetLivsvarigOffentligAfpSpecV3'][]
		}
		UttaksalderUtenlandsperiodeSpecV3: {
			/** Format: date */
			fom?: string
			/** Format: date */
			tom?: string
			landkode?: string
			arbeidetUtenlands?: boolean
		}
		UttaksalderResultV3: {
			/** Format: int32 */
			aar: number
			/** Format: int32 */
			maaneder: number
		}
		PensjonsavtaleAlderSpecV3: {
			/** Format: int32 */
			aar: number
			/** Format: int32 */
			maaneder: number
		}
		PensjonsavtaleInntektSpecV3: {
			/** Format: int32 */
			beloep: number
			sluttAlder?: components['schemas']['PensjonsavtaleAlderSpecV3']
		}
		PensjonsavtaleSpecV3: {
			/** Format: int32 */
			aarligInntektFoerUttakBeloep: number
			uttaksperioder: components['schemas']['PensjonsavtaleUttaksperiodeSpecV3'][]
			harAfp?: boolean
			/** @enum {string} */
			sivilstand?:
				| 'UNKNOWN'
				| 'UOPPGITT'
				| 'UGIFT'
				| 'GIFT'
				| 'ENKE_ELLER_ENKEMANN'
				| 'SKILT'
				| 'SEPARERT'
				| 'REGISTRERT_PARTNER'
				| 'SEPARERT_PARTNER'
				| 'SKILT_PARTNER'
				| 'GJENLEVENDE_PARTNER'
				| 'SAMBOER'
			epsHarInntektOver2G: boolean
			epsHarPensjon: boolean
		}
		PensjonsavtaleUttaksperiodeSpecV3: {
			startAlder: components['schemas']['PensjonsavtaleAlderSpecV3']
			/** Format: int32 */
			grad: number
			aarligInntektVsaPensjon?: components['schemas']['PensjonsavtaleInntektSpecV3']
		}
		Alder: {
			/** Format: int32 */
			aar: number
			/** Format: int32 */
			maaneder: number
		}
		PensjonsavtaleResultV3: {
			avtaler: components['schemas']['PensjonsavtaleV3'][]
			utilgjengeligeSelskap: components['schemas']['SelskapV3'][]
		}
		PensjonsavtaleV3: {
			produktbetegnelse: string
			/** @enum {string} */
			kategori: 'UNKNOWN' | 'INDIVIDUELL_ORDNING' | 'PRIVAT_TJENESTEPENSJON'
			/** Format: int32 */
			startAar: number
			/** Format: int32 */
			sluttAar?: number
			utbetalingsperioder: components['schemas']['UtbetalingsperiodeV3'][]
		}
		SelskapV3: {
			navn: string
			heltUtilgjengelig: boolean
		}
		UtbetalingsperiodeV3: {
			startAlder: components['schemas']['Alder']
			sluttAlder?: components['schemas']['Alder']
			/** Format: int32 */
			aarligUtbetaling: number
			/** Format: int32 */
			grad: number
		}
		SimuleringOffentligTjenestepensjonAlderV2: {
			/** Format: int32 */
			aar: number
			/** Format: int32 */
			maaneder: number
		}
		SimuleringOffentligTjenestepensjonGradertUttakV2: {
			uttaksalder: components['schemas']['SimuleringOffentligTjenestepensjonAlderV2']
			/** Format: int32 */
			aarligInntektVsaPensjonBeloep?: number
		}
		SimuleringOffentligTjenestepensjonHeltUttakV2: {
			uttaksalder: components['schemas']['SimuleringOffentligTjenestepensjonAlderV2']
			aarligInntektVsaPensjon?: components['schemas']['SimuleringOffentligTjenestepensjonInntektV2']
		}
		SimuleringOffentligTjenestepensjonInntektV2: {
			/** Format: int32 */
			beloep: number
			sluttAlder: components['schemas']['SimuleringOffentligTjenestepensjonAlderV2']
		}
		SimuleringOffentligTjenestepensjonSpecV2: {
			/** Format: date */
			foedselsdato: string
			/** Format: int32 */
			aarligInntektFoerUttakBeloep: number
			gradertUttak?: components['schemas']['SimuleringOffentligTjenestepensjonGradertUttakV2']
			heltUttak: components['schemas']['SimuleringOffentligTjenestepensjonHeltUttakV2']
			utenlandsperiodeListe: components['schemas']['UtenlandsoppholdV2'][]
			epsHarPensjon: boolean
			epsHarInntektOver2G: boolean
			brukerBaOmAfp: boolean
			erApoteker?: boolean
		}
		UtenlandsoppholdV2: {
			/** Format: date */
			fom: string
			/** Format: date */
			tom?: string
		}
		OffentligTjenestepensjonSimuleringResultV2: {
			/** @enum {string} */
			simuleringsresultatStatus:
				| 'OK'
				| 'BRUKER_ER_IKKE_MEDLEM_AV_TP_ORDNING'
				| 'TP_ORDNING_STOETTES_IKKE'
				| 'TOM_SIMULERING_FRA_TP_ORDNING'
				| 'TEKNISK_FEIL'
			muligeTpLeverandoerListe: string[]
			simulertTjenestepensjon?: components['schemas']['SimulertTjenestepensjonV2']
			serviceData?: string[]
		}
		SimuleringsresultatV2: {
			utbetalingsperioder: components['schemas']['UtbetalingsperiodeV2'][]
			betingetTjenestepensjonErInkludert: boolean
		}
		SimulertTjenestepensjonV2: {
			tpLeverandoer: string
			tpNummer: string
			simuleringsresultat: components['schemas']['SimuleringsresultatV2']
		}
		UtbetalingsperiodeV2: {
			startAlder: components['schemas']['Alder']
			sluttAlder?: components['schemas']['Alder']
			/** Format: int32 */
			aarligUtbetaling: number
			/** Format: int32 */
			maanedligUtbetaling?: number
		}
		SimuleringOffentligTjenestepensjonFoer1963SpecV1: {
			/** @enum {string} */
			simuleringstype:
				| 'ALDERSPENSJON'
				| 'PRE2025_OFFENTLIG_AFP_ETTERFULGT_AV_ALDERSPENSJON'
				| 'ALDERSPENSJON_MED_AFP_PRIVAT'
				| 'ALDERSPENSJON_MED_AFP_OFFENTLIG_LIVSVARIG'
				| 'ALDERSPENSJON_MED_GJENLEVENDERETT'
				| 'ENDRING_ALDERSPENSJON'
				| 'ENDRING_ALDERSPENSJON_MED_AFP_PRIVAT'
				| 'ENDRING_ALDERSPENSJON_MED_AFP_OFFENTLIG_LIVSVARIG'
				| 'ENDRING_ALDERSPENSJON_MED_GJENLEVENDERETT'
			/** Format: date */
			foedselsdato: string
			/** Format: int32 */
			aarligInntektFoerUttakBeloep?: number
			gradertUttak?: components['schemas']['PersonligSimuleringGradertUttakSpecV9']
			heltUttak: components['schemas']['PersonligSimuleringHeltUttakSpecV9']
			utenlandsperiodeListe?: components['schemas']['PersonligSimuleringUtenlandsperiodeSpecV9'][]
			/** @enum {string} */
			sivilstand?:
				| 'UNKNOWN'
				| 'UOPPGITT'
				| 'UGIFT'
				| 'GIFT'
				| 'ENKE_ELLER_ENKEMANN'
				| 'SKILT'
				| 'SEPARERT'
				| 'REGISTRERT_PARTNER'
				| 'SEPARERT_PARTNER'
				| 'SKILT_PARTNER'
				| 'GJENLEVENDE_PARTNER'
				| 'SAMBOER'
			epsHarInntektOver2G?: boolean
			epsHarPensjon?: boolean
			afpInntektMaanedFoerUttak?: boolean
			/** @enum {string} */
			afpOrdning?:
				| 'AFPKOM'
				| 'AFPSTAT'
				| 'FINANS'
				| 'KONV_K'
				| 'KONV_O'
				| 'LONHO'
				| 'NAVO'
			stillingsprosentOffHeltUttak: string
			stillingsprosentOffGradertUttak?: string
		}
		OffentligTjenestepensjonSimuleringFoer1963ResultV1: {
			/** @enum {string} */
			simuleringsresultatStatus:
				| 'OK'
				| 'BRUKER_ER_IKKE_MEDLEM_AV_TP_ORDNING'
				| 'TP_ORDNING_STOETTES_IKKE'
				| 'TOM_SIMULERING_FRA_TP_ORDNING'
				| 'TEKNISK_FEIL'
			muligeTpLeverandoerListe: string[]
			simulertTjenestepensjon?: components['schemas']['SimulertTjenestepensjonFoer1963V1']
			serviceData?: string[]
			/** @enum {string} */
			feilkode?:
				| 'TEKNISK_FEIL'
				| 'BEREGNING_GIR_NULL_UTBETALING'
				| 'BRUKER_IKKE_MEDLEM_AV_TP_ORDNING'
				| 'TP_ORDNING_STOETTES_IKKE'
				| 'OPPFYLLER_IKKE_INNGANGSVILKAAR'
		}
		SimuleringsresultatFoer1963V1: {
			utbetalingsperioder: components['schemas']['UtbetalingsperiodeFoer1963V1'][]
		}
		SimulertTjenestepensjonFoer1963V1: {
			tpLeverandoer: string
			tpNummer: string
			simuleringsresultat: components['schemas']['SimuleringsresultatFoer1963V1']
		}
		UtbetalingsperiodeFoer1963V1: {
			startAlder: components['schemas']['Alder']
			sluttAlder?: components['schemas']['Alder']
			/** Format: int32 */
			aarligUtbetaling: number
			/** Format: int32 */
			grad?: number
			/** @enum {string} */
			ytelsekode: 'AP' | 'AFP' | 'SERALDER'
			mangelfullSimuleringkode?: string
			/** Format: int32 */
			maanedligUtbetaling?: number
		}
		AnonymSimuleringAlderV1: {
			/** Format: int32 */
			aar: number
			/** Format: int32 */
			maaneder: number
		}
		AnonymSimuleringGradertUttakV1: {
			/** Format: int32 */
			grad: number
			uttaksalder: components['schemas']['AnonymSimuleringAlderV1']
			/** Format: int32 */
			aarligInntektVsaPensjonBeloep?: number
		}
		AnonymSimuleringHeltUttakV1: {
			uttaksalder: components['schemas']['AnonymSimuleringAlderV1']
			aarligInntektVsaPensjon?: components['schemas']['AnonymSimuleringInntektV1']
		}
		AnonymSimuleringInntektV1: {
			/** Format: int32 */
			beloep: number
			sluttAlder?: components['schemas']['AnonymSimuleringAlderV1']
		}
		AnonymSimuleringSpecV1: {
			/** @enum {string} */
			simuleringstype?: 'ALDERSPENSJON' | 'ALDERSPENSJON_MED_AFP_PRIVAT'
			/** Format: int32 */
			foedselAar: number
			/** @enum {string} */
			sivilstand?: 'UGIFT' | 'GIFT' | 'SAMBOER'
			epsHarInntektOver2G?: boolean
			epsHarPensjon?: boolean
			/** Format: int32 */
			utenlandsAntallAar?: number
			/** Format: int32 */
			inntektOver1GAntallAar?: number
			/** Format: int32 */
			aarligInntektFoerUttakBeloep?: number
			gradertUttak?: components['schemas']['AnonymSimuleringGradertUttakV1']
			heltUttak: components['schemas']['AnonymSimuleringHeltUttakV1']
		}
		AnonymSimuleringErrorV1: {
			status: string
			message: string
		}
		AnonymAlderV1: {
			/** Format: int32 */
			aar: number
			/** Format: int32 */
			maaneder: number
		}
		AnonymAlternativV1: {
			gradertUttaksalder?: components['schemas']['AnonymAlderV1']
			/** Format: int32 */
			uttaksgrad?: number
			heltUttaksalder: components['schemas']['AnonymAlderV1']
		}
		AnonymPensjonsberegningAfpOffentligV1: {
			/** Format: int32 */
			alder: number
			/** Format: int32 */
			beloep: number
		}
		AnonymPensjonsberegningV1: {
			/** Format: int32 */
			alder: number
			/** Format: int32 */
			beloep: number
		}
		AnonymSimuleringResultV1: {
			alderspensjon: components['schemas']['AnonymPensjonsberegningV1'][]
			afpPrivat?: components['schemas']['AnonymPensjonsberegningV1'][]
			afpOffentlig?: components['schemas']['AnonymPensjonsberegningAfpOffentligV1'][]
			vilkaarsproeving: components['schemas']['AnonymVilkaarsproevingV1']
		}
		AnonymVilkaarsproevingV1: {
			vilkaarErOppfylt: boolean
			alternativ?: components['schemas']['AnonymAlternativV1']
		}
		SimuleringV1AlderSpec: {
			/** Format: int32 */
			aar: number
			/** Format: int32 */
			maaneder: number
		}
		SimuleringV1AvdoedEps: {
			pid: string
			/** Format: date */
			doedsdato: string
			medlemAvFolketrygden?: boolean
			/** Format: int32 */
			inntektFoerDoedBeloep?: number
			inntektErOverGrunnbeloepet?: boolean
			/** Format: int32 */
			antallAarUtenlands?: number
		}
		SimuleringV1EpsSpec: {
			levende?: components['schemas']['SimuleringV1LevendeEps']
			avdoed?: components['schemas']['SimuleringV1AvdoedEps']
		}
		SimuleringV1GradertUttakSpec: {
			/** Format: int32 */
			grad: number
			uttaksalder: components['schemas']['SimuleringV1AlderSpec']
			/** Format: int32 */
			aarligInntektVsaPensjonBeloep?: number
		}
		SimuleringV1HeltUttakSpec: {
			uttaksalder: components['schemas']['SimuleringV1AlderSpec']
			aarligInntektVsaPensjon?: components['schemas']['SimuleringV1InntektSpec']
		}
		SimuleringV1InntektSpec: {
			/** Format: int32 */
			beloep: number
			sluttAlder: components['schemas']['SimuleringV1AlderSpec']
		}
		SimuleringV1InnvilgetLivsvarigOffentligAfpSpec: {
			/** Format: double */
			aarligBruttoBeloep: number
			/** Format: date */
			uttakFom: string
			/** Format: int32 */
			sistRegulertGrunnbeloep?: number
		}
		SimuleringV1LevendeEps: {
			harInntektOver2G: boolean
			harPensjon: boolean
		}
		SimuleringV1OffentligAfpSpec: {
			harInntektMaanedenFoerUttak?: boolean
			/** @enum {string} */
			afpOrdning?:
				| 'KOMMUNAL'
				| 'STATLIG'
				| 'FINANSNAERINGEN'
				| 'KONVERTERT_PRIVAT'
				| 'KONVERTERT_OFFENTLIG'
				| 'LO_NHO_ORDNINGEN'
				| 'SPEKTER'
			innvilgetLivsvarigAfpListe?: components['schemas']['SimuleringV1InnvilgetLivsvarigOffentligAfpSpec'][]
		}
		SimuleringV1Spec: {
			/** @enum {string} */
			simuleringstype:
				| 'ALDERSPENSJON'
				| 'ALDERSPENSJON_MED_TIDSBEGRENSET_OFFENTLIG_AFP'
				| 'ALDERSPENSJON_MED_LIVSVARIG_OFFENTLIG_AFP'
				| 'ALDERSPENSJON_MED_PRIVAT_AFP'
				| 'ALDERSPENSJON_MED_GJENLEVENDERETT'
				| 'ENDRING_ALDERSPENSJON'
				| 'ENDRING_ALDERSPENSJON_MED_LIVSVARIG_OFFENTLIG_AFP'
				| 'ENDRING_ALDERSPENSJON_MED_PRIVAT_AFP'
				| 'ENDRING_ALDERSPENSJON_MED_GJENLEVENDERETT'
			/** Format: int32 */
			aarligInntektFoerUttakBeloep?: number
			gradertUttak?: components['schemas']['SimuleringV1GradertUttakSpec']
			heltUttak: components['schemas']['SimuleringV1HeltUttakSpec']
			utenlandsperiodeListe?: components['schemas']['SimuleringV1UtenlandsperiodeSpec'][]
			/** @enum {string} */
			sivilstatus?:
				| 'UNKNOWN'
				| 'UOPPGITT'
				| 'UGIFT'
				| 'GIFT'
				| 'ENKE_ELLER_ENKEMANN'
				| 'SKILT'
				| 'SEPARERT'
				| 'REGISTRERT_PARTNER'
				| 'SEPARERT_PARTNER'
				| 'SKILT_PARTNER'
				| 'GJENLEVENDE_PARTNER'
				| 'SAMBOER'
			eps?: components['schemas']['SimuleringV1EpsSpec']
			offentligAfp?: components['schemas']['SimuleringV1OffentligAfpSpec']
		}
		SimuleringV1UtenlandsperiodeSpec: {
			/** Format: date */
			fom: string
			/** Format: date */
			tom?: string
			landkode: string
			arbeidetUtenlands: boolean
		}
		SimuleringV1AarligBeloep: {
			/**
			 * Format: int32
			 * @description Hvilket årstall (kalenderår) som informasjonen gjelder for
			 */
			aarstall: number
			/** Format: int32 */
			beloep: number
		}
		SimuleringV1Alder: {
			/**
			 * Format: int32
			 * @description Antall helt fylte år
			 */
			aar: number
			/**
			 * Format: int32
			 * @description Antall helt fylte måneder (0..11)
			 */
			maaneder: number
		}
		SimuleringV1AldersbestemtUtbetaling: {
			/**
			 * Format: int32
			 * @description Personens alder (år) som informasjonen gjelder for
			 */
			alderAar: number
			/** Format: int32 */
			aarligBeloep: number
			/** Format: int32 */
			maanedligBeloep?: number
		}
		SimuleringV1Alderspensjon: {
			/**
			 * Format: int32
			 * @description Personens alder (år) som informasjonen gjelder for
			 */
			alderAar: number
			/**
			 * Format: int32
			 * @description Årlig pensjonsbeløp
			 */
			beloep: number
			/**
			 * Format: int32
			 * @description Informasjon om gjenlevendetillegg er ikke inkludert i eksternvariant når funksjonsbryter 'utvidet-simuleringsresultat' er 'av'
			 */
			gjenlevendetillegg?: number
			/** @description Utvidet informasjon om alderspensjonen; kun inkludert i eksternvariant og kun når funksjonsbryter 'utvidet-simuleringsresultat' er 'på' */
			extension?: components['schemas']['SimuleringV1AlderspensjonExtension']
		}
		SimuleringV1AlderspensjonExtension: {
			/** Format: int32 */
			inntektspensjonBeloep?: number
			/** Format: int32 */
			garantipensjonBeloep?: number
			/** Format: double */
			delingstall?: number
			/** Format: int32 */
			pensjonBeholdningFoerUttakBeloep?: number
			/** Format: double */
			andelsbroekKap19?: number
			/** Format: double */
			andelsbroekKap20?: number
			/** Format: double */
			sluttpoengtall?: number
			/** Format: int32 */
			trygdetidKap19?: number
			/** Format: int32 */
			trygdetidKap20?: number
			/** Format: int32 */
			poengaarFoer92?: number
			/** Format: int32 */
			poengaarEtter91?: number
			/** Format: double */
			forholdstall?: number
			/** Format: int32 */
			grunnpensjon?: number
			/** Format: int32 */
			tilleggspensjon?: number
			/** Format: int32 */
			pensjonstillegg?: number
			/** Format: int32 */
			skjermingstillegg?: number
		}
		SimuleringV1PrivatAfp: {
			/**
			 * Format: int32
			 * @description Personens alder (år) som informasjonen gjelder for
			 */
			alderAar: number
			/** Format: int32 */
			aarligBeloep: number
			/** Format: int32 */
			kompensasjonstillegg: number
			/** Format: int32 */
			kronetillegg: number
			/** Format: int32 */
			livsvarig: number
			/** Format: int32 */
			maanedligBeloep?: number
		}
		SimuleringV1Problem: {
			/** @enum {string} */
			kode:
				| 'UGYLDIG_UTTAKSDATO'
				| 'UGYLDIG_UTTAKSGRAD'
				| 'UGYLDIG_SIVILSTATUS'
				| 'UGYLDIG_INNTEKT'
				| 'UGYLDIG_ANTALL_AAR'
				| 'UGYLDIG_PERSONIDENT'
				| 'PERSON_IKKE_FUNNET'
				| 'PERSON_FOR_HOEY_ALDER'
				| 'UTILSTREKKELIG_OPPTJENING'
				| 'UTILSTREKKELIG_TRYGDETID'
				| 'ANNEN_KLIENTFEIL'
				| 'SERVERFEIL'
			beskrivelse: string
		}
		SimuleringV1Result: {
			/** @description Alderspensjon for hvert år */
			alderspensjonListe: components['schemas']['SimuleringV1Alderspensjon'][]
			/** @description Månedlig alderspensjon ved endring av uttaksgrad */
			maanedligAlderspensjonVedUttaksendring?: components['schemas']['SimuleringV1Uttaksbeloep']
			/** @description Livsvarig AFP i offentlig sektor for hvert år */
			livsvarigOffentligAfpListe?: components['schemas']['SimuleringV1AldersbestemtUtbetaling'][]
			/** @description Tidsbegrenset AFP i offentlig sektor ('gammel ordning') for hvert år */
			tidsbegrensetOffentligAfp?: components['schemas']['SimuleringV1TidsbegrensetOffentligAfp']
			/** @description AFP i privat sektor for hvert år */
			privatAfpListe?: components['schemas']['SimuleringV1PrivatAfp'][]
			/** @description Resultatet av vilkårsprøvingen */
			vilkaarsproevingsresultat: components['schemas']['SimuleringV1Vilkaarsproevingsresultat']
			/** @description Personens trygdetid */
			trygdetid?: components['schemas']['SimuleringV1Trygdetid']
			/** @description Pensjonsgivende inntekter for hvert år */
			pensjonsgivendeInntektListe?: components['schemas']['SimuleringV1AarligBeloep'][]
			/** @description Eventelt problem som oppstod under simuleringen */
			problem?: components['schemas']['SimuleringV1Problem']
		}
		SimuleringV1TidsbegrensetOffentligAfp: {
			/**
			 * Format: int32
			 * @description Personens alder (år) som informasjonen gjelder for
			 */
			alderAar: number
			/** Format: int32 */
			totaltAfpBeloep: number
			/** Format: int32 */
			tidligereArbeidsinntekt: number
			/** Format: int32 */
			grunnbeloep: number
			/** Format: double */
			sluttpoengtall: number
			/** Format: int32 */
			trygdetid: number
			/** Format: int32 */
			poengaarTom1991: number
			/** Format: int32 */
			poengaarFom1992: number
			/** Format: int32 */
			grunnpensjon: number
			/** Format: int32 */
			tilleggspensjon: number
			/** Format: int32 */
			afpTillegg: number
			/** Format: int32 */
			saertillegg: number
			/** Format: int32 */
			afpGrad: number
			erAvkortet: boolean
		}
		SimuleringV1Trygdetid: {
			/** Format: int32 */
			antallAar: number
			erUtilstrekkelig: boolean
		}
		SimuleringV1Uttaksbeloep: {
			/**
			 * Format: int32
			 * @description Månedlig pensjonsbeløp ved start av gradert uttak
			 */
			gradertUttakMaanedligBeloep?: number
			/**
			 * Format: int32
			 * @description Månedlig pensjonsbeløp ved start av helt uttak
			 */
			heltUttakMaanedligBeloep: number
		}
		SimuleringV1Uttaksparametre: {
			gradertUttakAlder?: components['schemas']['SimuleringV1Alder']
			/** Format: int32 */
			uttaksgrad?: number
			heltUttakAlder: components['schemas']['SimuleringV1Alder']
		}
		SimuleringV1Vilkaarsproevingsresultat: {
			erInnvilget: boolean
			alternativ?: components['schemas']['SimuleringV1Uttaksparametre']
		}
		LagreAarligBeloepDto: {
			/** Format: int32 */
			aarstall: number
			/** Format: int32 */
			beloep: number
		}
		LagreAlderDto: {
			/** Format: int32 */
			aar: number
			/** Format: int32 */
			maaneder: number
		}
		LagreAldersbestemtUtbetalingDto: {
			/** Format: int32 */
			alderAar: number
			/** Format: int32 */
			aarligBeloep: number
			/** Format: int32 */
			maanedligBeloep?: number
		}
		LagreAlderspensjonDto: {
			/** Format: int32 */
			alderAar: number
			/** Format: int32 */
			beloep: number
			/** Format: int32 */
			gjenlevendetillegg?: number
		}
		LagrePrivatAfpDto: {
			/** Format: int32 */
			alderAar: number
			/** Format: int32 */
			aarligBeloep: number
			/** Format: int32 */
			kompensasjonstillegg: number
			/** Format: int32 */
			kronetillegg: number
			/** Format: int32 */
			livsvarig: number
			/** Format: int32 */
			maanedligBeloep?: number
		}
		LagreSimuleringSpecDtoV1: {
			alderspensjonListe: components['schemas']['LagreAlderspensjonDto'][]
			livsvarigOffentligAfpListe?: components['schemas']['LagreAldersbestemtUtbetalingDto'][]
			tidsbegrensetOffentligAfp?: components['schemas']['LagreTidsbegrensetOffentligAfpDto']
			privatAfpListe?: components['schemas']['LagrePrivatAfpDto'][]
			vilkaarsproevingsresultat: components['schemas']['LagreVilkaarsproevingsresultatDto']
			trygdetid?: components['schemas']['LagreTrygdetidDto']
			pensjonsgivendeInntektListe?: components['schemas']['LagreAarligBeloepDto'][]
			navEnhetId?: string
		}
		LagreTidsbegrensetOffentligAfpDto: {
			/** Format: int32 */
			alderAar: number
			/** Format: int32 */
			totaltAfpBeloep: number
			/** Format: int32 */
			tidligereArbeidsinntekt: number
			/** Format: int32 */
			grunnbeloep: number
			/** Format: double */
			sluttpoengtall: number
			/** Format: int32 */
			trygdetid: number
			/** Format: int32 */
			poengaarTom1991: number
			/** Format: int32 */
			poengaarFom1992: number
			/** Format: int32 */
			grunnpensjon: number
			/** Format: int32 */
			tilleggspensjon: number
			/** Format: int32 */
			afpTillegg: number
			/** Format: int32 */
			saertillegg: number
			/** Format: int32 */
			afpGrad: number
			erAvkortet: boolean
		}
		LagreTrygdetidDto: {
			/** Format: int32 */
			antallAar: number
			erUtilstrekkelig: boolean
		}
		LagreUttaksparametreDto: {
			gradertUttakAlder?: components['schemas']['LagreAlderDto']
			/** Format: int32 */
			uttaksgrad?: number
			heltUttakAlder: components['schemas']['LagreAlderDto']
		}
		LagreVilkaarsproevingsresultatDto: {
			erInnvilget: boolean
			alternativ?: components['schemas']['LagreUttaksparametreDto']
		}
		LagreSimuleringResponseDtoV1: {
			brevId?: string
			sakId?: string
			brevDevQ2Url?: string
		}
		EpsV1EpsSpec: {
			/** @enum {string} */
			sivilstatus?:
				| 'UNKNOWN'
				| 'UOPPGITT'
				| 'UGIFT'
				| 'GIFT'
				| 'ENKE_ELLER_ENKEMANN'
				| 'SKILT'
				| 'SEPARERT'
				| 'REGISTRERT_PARTNER'
				| 'SEPARERT_PARTNER'
				| 'SKILT_PARTNER'
				| 'GJENLEVENDE_PARTNER'
				| 'SAMBOER'
			bakgrunn?: string
		}
		EpsV1Familierelasjon: {
			pid?: string
			/** Format: date */
			fom?: string
			/** @enum {string} */
			relasjonstype: 'EKTEFELLE' | 'REGISTRERT_PARTNER' | 'SAMBOER'
			relasjonPersondata?: components['schemas']['EpsV1RelasjonPersondata']
		}
		EpsV1Navn: {
			fornavn?: string
			mellomnavn?: string
			etternavn?: string
		}
		EpsV1RelasjonPersondata: {
			/** @enum {string} */
			tilgangsbegrensning?:
				| 'FORTROLIG'
				| 'STRENGT_FORTROLIG'
				| 'STRENGT_FORTROLIG_UTLAND'
				| 'UNKNOWN'
			navn?: components['schemas']['EpsV1Navn']
			/** Format: date */
			foedselsdato?: string
			/** Format: date */
			doedsdato?: string
			statsborgerskap?: string
		}
		PersonV7Alder: {
			/** Format: int32 */
			aar: number
			/** Format: int32 */
			maaneder: number
		}
		PersonV7Pensjonsaldre: {
			normertPensjoneringsalder: components['schemas']['PersonV7Alder']
			nedreAldersgrense: components['schemas']['PersonV7Alder']
			oevreAldersgrense: components['schemas']['PersonV7Alder']
		}
		PersonV7Result: {
			navn: string
			fornavn: string
			/** Format: date */
			foedselsdato: string
			/** @enum {string} */
			sivilstatus:
				| 'UNKNOWN'
				| 'UOPPGITT'
				| 'UGIFT'
				| 'GIFT'
				| 'ENKE_ELLER_ENKEMANN'
				| 'SKILT'
				| 'SEPARERT'
				| 'REGISTRERT_PARTNER'
				| 'SEPARERT_PARTNER'
				| 'SKILT_PARTNER'
				| 'GJENLEVENDE_PARTNER'
				| 'SAMBOER'
			pensjoneringAldre: components['schemas']['PersonV7Pensjonsaldre']
		}
		PersonAlderV6: {
			/** Format: int32 */
			aar: number
			/** Format: int32 */
			maaneder: number
		}
		PersonPensjonsaldreV6: {
			normertPensjoneringsalder: components['schemas']['PersonAlderV6']
			nedreAldersgrense: components['schemas']['PersonAlderV6']
			oevreAldersgrense: components['schemas']['PersonAlderV6']
		}
		PersonResultV6: {
			navn: string
			fornavn: string
			/** Format: date */
			foedselsdato: string
			/** @enum {string} */
			sivilstand:
				| 'UNKNOWN'
				| 'UOPPGITT'
				| 'UGIFT'
				| 'GIFT'
				| 'ENKE_ELLER_ENKEMANN'
				| 'SKILT'
				| 'SEPARERT'
				| 'REGISTRERT_PARTNER'
				| 'SEPARERT_PARTNER'
				| 'SKILT_PARTNER'
				| 'GJENLEVENDE_PARTNER'
			pensjoneringAldre: components['schemas']['PersonPensjonsaldreV6']
		}
		AlderspensjonDetaljerV4: {
			/** Format: int32 */
			grad: number
			/** Format: date */
			fom: string
			/** Format: date */
			uttaksgradFom: string
			sisteUtbetaling?: components['schemas']['UtbetalingV4']
			/** @enum {string} */
			sivilstand:
				| 'UNKNOWN'
				| 'UOPPGITT'
				| 'UGIFT'
				| 'GIFT'
				| 'ENKE_ELLER_ENKEMANN'
				| 'SKILT'
				| 'SEPARERT'
				| 'REGISTRERT_PARTNER'
				| 'SEPARERT_PARTNER'
				| 'SKILT_PARTNER'
				| 'GJENLEVENDE_PARTNER'
				| 'SAMBOER'
		}
		FremtidigAlderspensjonDetaljerV4: {
			/** Format: int32 */
			grad: number
			/** Format: date */
			fom: string
		}
		LoependeFraV4: {
			/** Format: date */
			fom: string
		}
		LoependeVedtakV4: {
			harLoependeVedtak: boolean
			alderspensjon?: components['schemas']['AlderspensjonDetaljerV4']
			fremtidigAlderspensjon?: components['schemas']['FremtidigAlderspensjonDetaljerV4']
			ufoeretrygd: components['schemas']['UfoeretrygdDetaljerV4']
			afpPrivat?: components['schemas']['LoependeFraV4']
			afpOffentlig?: components['schemas']['LoependeFraV4']
			pre2025OffentligAfp?: components['schemas']['LoependeFraV4']
		}
		UfoeretrygdDetaljerV4: {
			/** Format: int32 */
			grad: number
		}
		UtbetalingV4: {
			beloep: number
			/** Format: date */
			utbetalingsdato: string
		}
		LivsvarigOffentligAfpResultV3: {
			afpInnvilget?: boolean
			maanedligBeloepListe?: components['schemas']['MaanedligBeloepV3'][]
			/** Format: date */
			virkningFom?: string
			/** Format: int32 */
			sistBenyttetGrunnbeloep?: number
		}
		MaanedligBeloepV3: {
			/** Format: date */
			virkningFom?: string
			/** Format: int32 */
			beloep?: number
		}
		LivsvarigOffentligAfpResultV2: {
			afpStatus?: boolean
			/** Format: date */
			virkningFom?: string
			/** Format: int32 */
			maanedligBeloep?: number
			/** Format: int32 */
			sistBenyttetGrunnbeloep?: number
		}
		EkskluderingStatusV2: {
			ekskludert: boolean
			/** @enum {string} */
			aarsak: 'NONE' | 'ER_APOTEKER'
		}
		VedtakV1Alderspensjonsuttak: {
			/**
			 * Format: int32
			 * @description Uttaksgrad (prosent) for alderspensjonen
			 */
			grad: number
			/**
			 * Format: date
			 * @description Startdato (fra og med) for alderspensjonen
			 */
			fom: string
		}
		VedtakV1LoependeAlderspensjon: {
			/**
			 * Format: int32
			 * @description Uttaksgrad (prosent) for alderspensjonen
			 */
			grad: number
			/**
			 * Format: date
			 * @description Startdato (fra og med) for alderspensjonen
			 */
			fom: string
			/**
			 * Format: date
			 * @description Startdato (fra og med) for uttaksgraden
			 */
			uttaksgradFom: string
			/** @description Siste utbetaling av alderspensjon */
			sisteUtbetaling?: components['schemas']['VedtakV1Utbetaling']
			/**
			 * @description Sivilstatus
			 * @enum {string}
			 */
			sivilstatus:
				| 'UNKNOWN'
				| 'UOPPGITT'
				| 'UGIFT'
				| 'GIFT'
				| 'ENKE_ELLER_ENKEMANN'
				| 'SKILT'
				| 'SEPARERT'
				| 'REGISTRERT_PARTNER'
				| 'SEPARERT_PARTNER'
				| 'SKILT_PARTNER'
				| 'GJENLEVENDE_PARTNER'
				| 'SAMBOER'
		}
		VedtakV1Samling: {
			/** @description Om personen har løpende vedtak */
			harVedtak: boolean
			/** @description Løpende alderspensjon */
			loependeAlderspensjon?: components['schemas']['VedtakV1LoependeAlderspensjon']
			/** @description Fremtidig alderspensjon */
			fremtidigAlderspensjon?: components['schemas']['VedtakV1Alderspensjonsuttak']
			/**
			 * Format: int32
			 * @description Grad av uføretrygd (0-100)
			 */
			ufoeretrygdgrad?: number
			/**
			 * Format: date
			 * @description Startdato (fra og med) for AFP i privat sektor
			 */
			privatAfpFom?: string
			/**
			 * Format: date
			 * @description Startdato (fra og med) for tidsbegrenset AFP i offentlig sektor ('gammel ordning')
			 */
			tidsbegrensetOffentligAfpFom?: string
		}
		VedtakV1Utbetaling: {
			/** @description Beløp utbetalt */
			beloep: number
			/**
			 * Format: date
			 * @description Dato for utbetalingen
			 */
			utbetalingsdato: string
		}
		UfoeregradDto: {
			/** Format: int32 */
			ufoeregrad: number
		}
		MedlemskapITjenestepensjonsordningDto: {
			tpLeverandoerListe: string[]
		}
		BrukerHarLoependeOmstillingsstoenadEllerGjenlevendeYtelse: {
			harLoependeSak: boolean
		}
		LandInfo: {
			landkode: string
			kravOmArbeid?: boolean
			bokmaalNavn: string
			nynorskNavn: string
			engelskNavn: string
		}
		ApotekerStatusV1: {
			apoteker: boolean
			/** @enum {string} */
			aarsak: 'NONE' | 'ER_APOTEKER'
		}
		EkskluderingStatusV1: {
			ekskludert: boolean
			/** @enum {string} */
			aarsak:
				| 'NONE'
				| 'HAR_LOEPENDE_UFOERETRYGD'
				| 'HAR_GJENLEVENDEYTELSE'
				| 'ER_APOTEKER'
		}
		AnsattV1: {
			id: string
		}
		TjenestepensjonsforholdDto: {
			harTjenestepensjonsforhold: boolean
		}
		ApiStatusDto: {
			status: string
		}
		SakDto: {
			harUfoeretrygdEllerGjenlevendeytelse: boolean
		}
		EpsV1SivilstatusResult: {
			/** @enum {string} */
			sivilstatus:
				| 'UNKNOWN'
				| 'UOPPGITT'
				| 'UGIFT'
				| 'GIFT'
				| 'ENKE_ELLER_ENKEMANN'
				| 'SKILT'
				| 'SEPARERT'
				| 'REGISTRERT_PARTNER'
				| 'SEPARERT_PARTNER'
				| 'SKILT_PARTNER'
				| 'GJENLEVENDE_PARTNER'
				| 'SAMBOER'
		}
		PersonInternV1Alder: {
			/** Format: int32 */
			aar: number
			/** Format: int32 */
			maaneder: number
		}
		PersonInternV1Pensjonsaldre: {
			normertPensjoneringsalder: components['schemas']['PersonInternV1Alder']
			nedreAldersgrense: components['schemas']['PersonInternV1Alder']
			oevreAldersgrense: components['schemas']['PersonInternV1Alder']
		}
		PersonInternV1Person: {
			navn: string
			/** Format: date */
			foedselsdato: string
			/** @enum {string} */
			sivilstatus:
				| 'UNKNOWN'
				| 'UOPPGITT'
				| 'UGIFT'
				| 'GIFT'
				| 'ENKE_ELLER_ENKEMANN'
				| 'SKILT'
				| 'SEPARERT'
				| 'REGISTRERT_PARTNER'
				| 'SEPARERT_PARTNER'
				| 'SKILT_PARTNER'
				| 'GJENLEVENDE_PARTNER'
				| 'SAMBOER'
			pensjoneringAldre: components['schemas']['PersonInternV1Pensjonsaldre']
		}
		InntektDto: {
			/** Format: int32 */
			beloep: number
			/** Format: int32 */
			aar: number
		}
		EnablementDto: {
			enabled: boolean
		}
	}
	responses: never
	parameters: never
	requestBodies: never
	headers: never
	pathItems: never
}
export type $defs = Record<string, never>
export interface operations {
	simulerAlderspensjonV9: {
		parameters: {
			query?: never
			header?: never
			path?: never
			cookie?: never
		}
		requestBody: {
			content: {
				'application/json': components['schemas']['PersonligSimuleringSpecV9']
			}
		}
		responses: {
			/** @description Simulering utført */
			200: {
				headers: {
					[name: string]: unknown
				}
				content: {
					'*/*': components['schemas']['PersonligSimuleringResultV9']
				}
			}
			/** @description Simulering kunne ikke utføres av tekniske årsaker */
			503: {
				headers: {
					[name: string]: unknown
				}
				content: {
					/**
					 * @example {
					 *       "timestamp": "2023-09-12T10:37:47.056+00:00",
					 *       "status": 503,
					 *       "error": "Service Unavailable",
					 *       "message": "En feil inntraff",
					 *       "path": "/api/ressurs"
					 *     }
					 */
					'*/*': unknown
				}
			}
		}
	}
	finnTidligsteHelUttaksalderV3: {
		parameters: {
			query?: never
			header?: never
			path?: never
			cookie?: never
		}
		requestBody: {
			content: {
				'application/json': components['schemas']['UttaksalderSpecV3']
			}
		}
		responses: {
			/** @description Søk etter uttaksalder utført. I resultatet er verdi av 'maaneder' 0..11. */
			200: {
				headers: {
					[name: string]: unknown
				}
				content: {
					'*/*': components['schemas']['UttaksalderResultV3']
				}
			}
			/** @description Søk etter uttaksalder kunne ikke utføres av tekniske årsaker */
			503: {
				headers: {
					[name: string]: unknown
				}
				content: {
					/**
					 * @example {
					 *       "timestamp": "2023-09-12T10:37:47.056+00:00",
					 *       "status": 503,
					 *       "error": "Service Unavailable",
					 *       "message": "En feil inntraff",
					 *       "path": "/api/ressurs"
					 *     }
					 */
					'*/*': unknown
				}
			}
		}
	}
	fetchAvtalerV3: {
		parameters: {
			query?: never
			header?: never
			path?: never
			cookie?: never
		}
		requestBody: {
			content: {
				'application/json': components['schemas']['PensjonsavtaleSpecV3']
			}
		}
		responses: {
			/** @description Henting av pensjonsavtaler utført. I respons er verdi av 'maaneder' 0..11. */
			200: {
				headers: {
					[name: string]: unknown
				}
				content: {
					'*/*': components['schemas']['PensjonsavtaleResultV3']
				}
			}
			/** @description Henting av pensjonsavtaler kunne ikke utføres av tekniske årsaker */
			503: {
				headers: {
					[name: string]: unknown
				}
				content: {
					/**
					 * @example {
					 *       "timestamp": "2023-09-12T10:37:47.056+00:00",
					 *       "status": 503,
					 *       "error": "Service Unavailable",
					 *       "message": "En feil inntraff",
					 *       "path": "/api/ressurs"
					 *     }
					 */
					'*/*': unknown
				}
			}
		}
	}
	simulerOffentligTjenestepensjonV2: {
		parameters: {
			query?: never
			header?: never
			path?: never
			cookie?: never
		}
		requestBody: {
			content: {
				'application/json': components['schemas']['SimuleringOffentligTjenestepensjonSpecV2']
			}
		}
		responses: {
			/** @description OK */
			200: {
				headers: {
					[name: string]: unknown
				}
				content: {
					'*/*': components['schemas']['OffentligTjenestepensjonSimuleringResultV2']
				}
			}
		}
	}
	simulerOffentligTjenestepensjonFoer1963V1: {
		parameters: {
			query?: never
			header?: never
			path?: never
			cookie?: never
		}
		requestBody: {
			content: {
				'application/json': components['schemas']['SimuleringOffentligTjenestepensjonFoer1963SpecV1']
			}
		}
		responses: {
			/** @description OK */
			200: {
				headers: {
					[name: string]: unknown
				}
				content: {
					'*/*': components['schemas']['OffentligTjenestepensjonSimuleringFoer1963ResultV1']
				}
			}
		}
	}
	encrypt: {
		parameters: {
			query?: never
			header?: never
			path?: never
			cookie?: never
		}
		requestBody: {
			content: {
				'application/json': string
			}
		}
		responses: {
			/** @description Kryptering utført */
			200: {
				headers: {
					[name: string]: unknown
				}
				content: {
					'*/*': string
				}
			}
			/** @description Kryptering kunne ikke utføres av tekniske årsaker */
			503: {
				headers: {
					[name: string]: unknown
				}
				content: {
					/**
					 * @example {
					 *       "timestamp": "2023-09-12T10:37:47.056+00:00",
					 *       "status": 503,
					 *       "error": "Service Unavailable",
					 *       "message": "En feil inntraff",
					 *       "path": "/api/ressurs"
					 *     }
					 */
					'*/*': unknown
				}
			}
		}
	}
	decrypt: {
		parameters: {
			query?: never
			header?: never
			path?: never
			cookie?: never
		}
		requestBody: {
			content: {
				'application/json': string
			}
		}
		responses: {
			/** @description Dekryptering utført */
			200: {
				headers: {
					[name: string]: unknown
				}
				content: {
					'*/*': string
				}
			}
			/** @description Dekryptering kunne ikke utføres av tekniske årsaker */
			503: {
				headers: {
					[name: string]: unknown
				}
				content: {
					/**
					 * @example {
					 *       "timestamp": "2023-09-12T10:37:47.056+00:00",
					 *       "status": 503,
					 *       "error": "Service Unavailable",
					 *       "message": "En feil inntraff",
					 *       "path": "/api/ressurs"
					 *     }
					 */
					'*/*': unknown
				}
			}
		}
	}
	simulerAnonymAlderspensjonV1: {
		parameters: {
			query?: never
			header?: never
			path?: never
			cookie?: never
		}
		requestBody: {
			content: {
				'application/json': components['schemas']['AnonymSimuleringSpecV1']
			}
		}
		responses: {
			/** @description Simulering utført */
			200: {
				headers: {
					[name: string]: unknown
				}
				content: {
					'*/*': components['schemas']['AnonymSimuleringResultV1']
				}
			}
			/** @description Simulering kunne ikke utføres pga. feil i input-data */
			'4xx': {
				headers: {
					[name: string]: unknown
				}
				content: {
					'*/*': components['schemas']['AnonymSimuleringErrorV1']
				}
			}
		}
	}
	simulerPensjon: {
		parameters: {
			query?: never
			header?: never
			path?: never
			cookie?: never
		}
		requestBody: {
			content: {
				'application/json': components['schemas']['SimuleringV1Spec']
			}
		}
		responses: {
			/** @description Simulering utført */
			200: {
				headers: {
					[name: string]: unknown
				}
				content: {
					'*/*': components['schemas']['SimuleringV1Result']
				}
			}
			/** @description Simulering kunne ikke utføres pga. uakseptable inndata. */
			400: {
				headers: {
					[name: string]: unknown
				}
				content: {
					'*/*': components['schemas']['SimuleringV1Result']
				}
			}
			/** @description Simulering kunne ikke utføres pga. manglende/feilaktig autentisering. */
			401: {
				headers: {
					[name: string]: unknown
				}
				content: {
					'*/*': components['schemas']['SimuleringV1Result']
				}
			}
			/** @description Simulering kunne ikke utføres pga. manglende tilgang til tjenesten. */
			403: {
				headers: {
					[name: string]: unknown
				}
				content: {
					'*/*': components['schemas']['SimuleringV1Result']
				}
			}
			/** @description Simulering kunne ikke utføres fordi angitt person ikke finnes i systemet. */
			404: {
				headers: {
					[name: string]: unknown
				}
				content: {
					'*/*': components['schemas']['SimuleringV1Result']
				}
			}
			/** @description Simulering kunne ikke utføres pga. feil i systemet. */
			500: {
				headers: {
					[name: string]: unknown
				}
				content: {
					'*/*': components['schemas']['SimuleringV1Result']
				}
			}
		}
	}
	lagreSimuleringV1: {
		parameters: {
			query?: never
			header?: never
			path?: never
			cookie?: never
		}
		requestBody: {
			content: {
				'application/json': components['schemas']['LagreSimuleringSpecDtoV1']
			}
		}
		responses: {
			/** @description Lagring utført */
			200: {
				headers: {
					[name: string]: unknown
				}
				content: {
					'*/*': components['schemas']['LagreSimuleringResponseDtoV1']
				}
			}
			/** @description Lagring kunne ikke utføres av tekniske årsaker */
			503: {
				headers: {
					[name: string]: unknown
				}
				content: {
					'*/*': components['schemas']['LagreSimuleringResponseDtoV1']
				}
			}
		}
	}
	nyligsteEps: {
		parameters: {
			query?: never
			header?: never
			path?: never
			cookie?: never
		}
		requestBody: {
			content: {
				'application/json': components['schemas']['EpsV1EpsSpec']
			}
		}
		responses: {
			/** @description Henting av EPS utført. */
			200: {
				headers: {
					[name: string]: unknown
				}
				content: {
					'*/*': components['schemas']['EpsV1Familierelasjon']
				}
			}
			/** @description Henting av EPS kunne ikke utføres av tekniske årsaker. */
			503: {
				headers: {
					[name: string]: unknown
				}
				content: {
					/**
					 * @example {
					 *       "timestamp": "2023-09-12T10:37:47.056+00:00",
					 *       "status": 503,
					 *       "error": "Service Unavailable",
					 *       "message": "En feil inntraff",
					 *       "path": "/api/ressurs"
					 *     }
					 */
					'*/*': unknown
				}
			}
		}
	}
	simulerPensjon_1: {
		parameters: {
			query?: never
			header?: never
			path?: never
			cookie?: never
		}
		requestBody: {
			content: {
				'application/json': components['schemas']['SimuleringV1Spec']
			}
		}
		responses: {
			/** @description Simulering utført */
			200: {
				headers: {
					[name: string]: unknown
				}
				content: {
					'*/*': components['schemas']['SimuleringV1Result']
				}
			}
			/** @description Simulering kunne ikke utføres pga. uakseptable inndata. */
			400: {
				headers: {
					[name: string]: unknown
				}
				content: {
					'*/*': components['schemas']['SimuleringV1Result']
				}
			}
			/** @description Simulering kunne ikke utføres pga. manglende/feilaktig autentisering. */
			401: {
				headers: {
					[name: string]: unknown
				}
				content: {
					'*/*': components['schemas']['SimuleringV1Result']
				}
			}
			/** @description Simulering kunne ikke utføres pga. manglende tilgang til tjenesten. */
			403: {
				headers: {
					[name: string]: unknown
				}
				content: {
					'*/*': components['schemas']['SimuleringV1Result']
				}
			}
			/** @description Simulering kunne ikke utføres fordi angitt person ikke finnes i systemet. */
			404: {
				headers: {
					[name: string]: unknown
				}
				content: {
					'*/*': components['schemas']['SimuleringV1Result']
				}
			}
			/** @description Simulering kunne ikke utføres pga. feil i systemet. */
			500: {
				headers: {
					[name: string]: unknown
				}
				content: {
					'*/*': components['schemas']['SimuleringV1Result']
				}
			}
		}
	}
	person: {
		parameters: {
			query?: never
			header?: never
			path?: never
			cookie?: never
		}
		requestBody?: never
		responses: {
			/** @description Henting av personinformasjon utført. */
			200: {
				headers: {
					[name: string]: unknown
				}
				content: {
					'*/*': components['schemas']['PersonV7Result']
				}
			}
			/** @description Personen ble ikke funnet. */
			404: {
				headers: {
					[name: string]: unknown
				}
				content: {
					'*/*': components['schemas']['PersonV7Result']
				}
			}
			/** @description Henting av personinformasjon kunne ikke utføres av tekniske årsaker. */
			503: {
				headers: {
					[name: string]: unknown
				}
				content: {
					/**
					 * @example {
					 *       "timestamp": "2023-09-12T10:37:47.056+00:00",
					 *       "status": 503,
					 *       "error": "Service Unavailable",
					 *       "message": "En feil inntraff",
					 *       "path": "/api/ressurs"
					 *     }
					 */
					'*/*': unknown
				}
			}
		}
	}
	personV6: {
		parameters: {
			query?: never
			header?: never
			path?: never
			cookie?: never
		}
		requestBody?: never
		responses: {
			/** @description Henting av personinformasjon utført. */
			200: {
				headers: {
					[name: string]: unknown
				}
				content: {
					'*/*': components['schemas']['PersonResultV6']
				}
			}
			/** @description Personen ble ikke funnet. */
			404: {
				headers: {
					[name: string]: unknown
				}
				content: {
					'*/*': components['schemas']['PersonResultV6']
				}
			}
			/** @description Henting av personinformasjon kunne ikke utføres av tekniske årsaker. */
			503: {
				headers: {
					[name: string]: unknown
				}
				content: {
					/**
					 * @example {
					 *       "timestamp": "2023-09-12T10:37:47.056+00:00",
					 *       "status": 503,
					 *       "error": "Service Unavailable",
					 *       "message": "En feil inntraff",
					 *       "path": "/api/ressurs"
					 *     }
					 */
					'*/*': unknown
				}
			}
		}
	}
	hentLoependeVedtakV4: {
		parameters: {
			query?: never
			header?: never
			path?: never
			cookie?: never
		}
		requestBody?: never
		responses: {
			/** @description Henting av løpende vedtak utført */
			200: {
				headers: {
					[name: string]: unknown
				}
				content: {
					'*/*': components['schemas']['LoependeVedtakV4']
				}
			}
			/** @description Henting av løpende vedtak kunne ikke utføres av tekniske årsaker */
			503: {
				headers: {
					[name: string]: unknown
				}
				content: {
					/**
					 * @example {
					 *       "timestamp": "2023-09-12T10:37:47.056+00:00",
					 *       "status": 503,
					 *       "error": "Service Unavailable",
					 *       "message": "En feil inntraff",
					 *       "path": "/api/ressurs"
					 *     }
					 */
					'*/*': unknown
				}
			}
		}
	}
	hentLivsvarigOffentligAfpDetaljerV3: {
		parameters: {
			query?: never
			header?: never
			path?: never
			cookie?: never
		}
		requestBody?: never
		responses: {
			/** @description OK */
			200: {
				headers: {
					[name: string]: unknown
				}
				content: {
					'*/*': components['schemas']['LivsvarigOffentligAfpResultV3']
				}
			}
		}
	}
	hentLivsvarigOffentligAfpDetaljer: {
		parameters: {
			query?: never
			header?: never
			path?: never
			cookie?: never
		}
		requestBody?: never
		responses: {
			/** @description OK */
			200: {
				headers: {
					[name: string]: unknown
				}
				content: {
					'*/*': components['schemas']['LivsvarigOffentligAfpResultV2']
				}
			}
		}
	}
	erEkskludertV2: {
		parameters: {
			query?: never
			header?: never
			path?: never
			cookie?: never
		}
		requestBody?: never
		responses: {
			/** @description Sjekking av ekskludering utført */
			200: {
				headers: {
					[name: string]: unknown
				}
				content: {
					'*/*': components['schemas']['EkskluderingStatusV2']
				}
			}
			/** @description Sjekking av ekskludering kunne ikke utføres av tekniske årsaker */
			503: {
				headers: {
					[name: string]: unknown
				}
				content: {
					/**
					 * @example {
					 *       "timestamp": "2023-09-12T10:37:47.056+00:00",
					 *       "status": 503,
					 *       "error": "Service Unavailable",
					 *       "message": "En feil inntraff",
					 *       "path": "/api/ressurs"
					 *     }
					 */
					'*/*': unknown
				}
			}
		}
	}
	hentVedtak: {
		parameters: {
			query?: never
			header?: never
			path?: never
			cookie?: never
		}
		requestBody?: never
		responses: {
			/** @description Henting av vedtak utført. */
			200: {
				headers: {
					[name: string]: unknown
				}
				content: {
					'*/*': components['schemas']['VedtakV1Samling']
				}
			}
			/** @description Tjenesten kunne ikke utføres pga. uakseptable inndata. */
			400: {
				headers: {
					[name: string]: unknown
				}
				content: {
					'*/*': components['schemas']['VedtakV1Samling']
				}
			}
			/** @description Tjenesten kunne ikke utføres pga. manglende/feilaktig autentisering. */
			401: {
				headers: {
					[name: string]: unknown
				}
				content: {
					'*/*': components['schemas']['VedtakV1Samling']
				}
			}
			/** @description Tjenesten kunne ikke utføres pga. manglende tilgang til tjenesten. */
			403: {
				headers: {
					[name: string]: unknown
				}
				content: {
					'*/*': components['schemas']['VedtakV1Samling']
				}
			}
			/** @description Tjenesten kunne ikke utføres fordi angitt person ikke finnes i systemet. */
			404: {
				headers: {
					[name: string]: unknown
				}
				content: {
					'*/*': components['schemas']['VedtakV1Samling']
				}
			}
			/** @description Tjenesten kunne ikke utføres pga. feil i systemet. */
			500: {
				headers: {
					[name: string]: unknown
				}
				content: {
					'*/*': components['schemas']['VedtakV1Samling']
				}
			}
		}
	}
	hentUfoeregrad: {
		parameters: {
			query?: never
			header?: never
			path?: never
			cookie?: never
		}
		requestBody?: never
		responses: {
			/** @description Henting av uføregrad utført */
			200: {
				headers: {
					[name: string]: unknown
				}
				content: {
					'*/*': components['schemas']['UfoeregradDto']
				}
			}
			/** @description henting av uføregrad kunne ikke utføres av tekniske årsaker */
			503: {
				headers: {
					[name: string]: unknown
				}
				content: {
					/**
					 * @example {
					 *       "timestamp": "2023-09-12T10:37:47.056+00:00",
					 *       "status": 503,
					 *       "error": "Service Unavailable",
					 *       "message": "En feil inntraff",
					 *       "path": "/api/ressurs"
					 *     }
					 */
					'*/*': unknown
				}
			}
		}
	}
	hentMedlemskapITjenestepensjonsordninger: {
		parameters: {
			query?: never
			header?: never
			path?: never
			cookie?: never
		}
		requestBody?: never
		responses: {
			/** @description OK */
			200: {
				headers: {
					[name: string]: unknown
				}
				content: {
					'*/*': components['schemas']['MedlemskapITjenestepensjonsordningDto']
				}
			}
		}
	}
	mottarOmstillingsstoenadEllerGjenlevendeYtelse: {
		parameters: {
			query?: never
			header?: never
			path?: never
			cookie?: never
		}
		requestBody?: never
		responses: {
			/** @description Henting av omstillingsstønad eller gjenlevende ytelse utført. */
			200: {
				headers: {
					[name: string]: unknown
				}
				content: {
					'*/*': components['schemas']['BrukerHarLoependeOmstillingsstoenadEllerGjenlevendeYtelse']
				}
			}
			/** @description Henting av omstillingsstønad eller gjenlevende ytelse kunne ikke utføres av tekniske årsaker */
			503: {
				headers: {
					[name: string]: unknown
				}
				content: {
					/**
					 * @example {
					 *       "timestamp": "2023-09-12T10:37:47.056+00:00",
					 *       "status": 503,
					 *       "error": "Service Unavailable",
					 *       "message": "En feil inntraff",
					 *       "path": "/api/ressurs"
					 *     }
					 */
					'*/*': unknown
				}
			}
		}
	}
	landListe: {
		parameters: {
			query?: never
			header?: never
			path?: never
			cookie?: never
		}
		requestBody?: never
		responses: {
			/** @description Henting av land-liste utført. */
			200: {
				headers: {
					[name: string]: unknown
				}
				content: {
					'*/*': components['schemas']['LandInfo'][]
				}
			}
			/** @description Henting av land-liste kunne ikke utføres av tekniske årsaker. */
			503: {
				headers: {
					[name: string]: unknown
				}
				content: {
					/**
					 * @example {
					 *       "timestamp": "2023-09-12T10:37:47.056+00:00",
					 *       "status": 503,
					 *       "error": "Service Unavailable",
					 *       "message": "En feil inntraff",
					 *       "path": "/api/ressurs"
					 *     }
					 */
					'*/*': unknown
				}
			}
		}
	}
	erApotekerV1: {
		parameters: {
			query?: never
			header?: never
			path?: never
			cookie?: never
		}
		requestBody?: never
		responses: {
			/** @description Sjekking av apoteker utført */
			200: {
				headers: {
					[name: string]: unknown
				}
				content: {
					'*/*': components['schemas']['ApotekerStatusV1']
				}
			}
			/** @description Sjekking av apoteker kunne ikke utføres av tekniske årsaker */
			503: {
				headers: {
					[name: string]: unknown
				}
				content: {
					/**
					 * @example {
					 *       "timestamp": "2023-09-12T10:37:47.056+00:00",
					 *       "status": 503,
					 *       "error": "Service Unavailable",
					 *       "message": "En feil inntraff",
					 *       "path": "/api/ressurs"
					 *     }
					 */
					'*/*': unknown
				}
			}
		}
	}
	erEkskludertV1: {
		parameters: {
			query?: never
			header?: never
			path?: never
			cookie?: never
		}
		requestBody?: never
		responses: {
			/** @description Sjekking av ekskludering utført */
			200: {
				headers: {
					[name: string]: unknown
				}
				content: {
					'*/*': components['schemas']['EkskluderingStatusV1']
				}
			}
			/** @description Sjekking av ekskludering kunne ikke utføres av tekniske årsaker */
			503: {
				headers: {
					[name: string]: unknown
				}
				content: {
					/**
					 * @example {
					 *       "timestamp": "2023-09-12T10:37:47.056+00:00",
					 *       "status": 503,
					 *       "error": "Service Unavailable",
					 *       "message": "En feil inntraff",
					 *       "path": "/api/ressurs"
					 *     }
					 */
					'*/*': unknown
				}
			}
		}
	}
	ansattId: {
		parameters: {
			query?: never
			header?: never
			path?: never
			cookie?: never
		}
		requestBody?: never
		responses: {
			/** @description Henting av ansatt-ID utført. */
			200: {
				headers: {
					[name: string]: unknown
				}
				content: {
					'*/*': components['schemas']['AnsattV1']
				}
			}
			/** @description Henting av ansatt-ID kunne ikke utføres av tekniske årsaker. */
			503: {
				headers: {
					[name: string]: unknown
				}
				content: {
					/**
					 * @example {
					 *       "timestamp": "2023-09-12T10:37:47.056+00:00",
					 *       "status": 503,
					 *       "error": "Service Unavailable",
					 *       "message": "En feil inntraff",
					 *       "path": "/api/ressurs"
					 *     }
					 */
					'*/*': unknown
				}
			}
		}
	}
	harTjenestepensjonsforhold: {
		parameters: {
			query?: never
			header?: never
			path?: never
			cookie?: never
		}
		requestBody?: never
		responses: {
			/** @description OK */
			200: {
				headers: {
					[name: string]: unknown
				}
				content: {
					'*/*': components['schemas']['TjenestepensjonsforholdDto']
				}
			}
		}
	}
	status: {
		parameters: {
			query?: never
			header?: never
			path?: never
			cookie?: never
		}
		requestBody?: never
		responses: {
			/** @description OK */
			200: {
				headers: {
					[name: string]: unknown
				}
				content: {
					'*/*': components['schemas']['ApiStatusDto']
				}
			}
		}
	}
	harRelevantSak: {
		parameters: {
			query?: never
			header?: never
			path?: never
			cookie?: never
		}
		requestBody?: never
		responses: {
			/** @description Sjekking av saker utført */
			200: {
				headers: {
					[name: string]: unknown
				}
				content: {
					'*/*': components['schemas']['SakDto']
				}
			}
			/** @description Sjekking av saker kunne ikke utføres av tekniske årsaker */
			503: {
				headers: {
					[name: string]: unknown
				}
				content: {
					/**
					 * @example {
					 *       "timestamp": "2023-09-12T10:37:47.056+00:00",
					 *       "status": 503,
					 *       "error": "Service Unavailable",
					 *       "message": "En feil inntraff",
					 *       "path": "/api/ressurs"
					 *     }
					 */
					'*/*': unknown
				}
			}
		}
	}
	naavaerendeSivilstatus: {
		parameters: {
			query?: never
			header?: never
			path?: never
			cookie?: never
		}
		requestBody?: never
		responses: {
			/** @description Henting av sivilstatus utført. */
			200: {
				headers: {
					[name: string]: unknown
				}
				content: {
					'*/*': components['schemas']['EpsV1SivilstatusResult']
				}
			}
			/** @description Henting av sivilstatus kunne ikke utføres av tekniske årsaker. */
			503: {
				headers: {
					[name: string]: unknown
				}
				content: {
					/**
					 * @example {
					 *       "timestamp": "2023-09-12T10:37:47.056+00:00",
					 *       "status": 503,
					 *       "error": "Service Unavailable",
					 *       "message": "En feil inntraff",
					 *       "path": "/api/ressurs"
					 *     }
					 */
					'*/*': unknown
				}
			}
		}
	}
	personV1: {
		parameters: {
			query?: never
			header?: never
			path?: never
			cookie?: never
		}
		requestBody?: never
		responses: {
			/** @description Henting av personinformasjon utført. */
			200: {
				headers: {
					[name: string]: unknown
				}
				content: {
					'*/*': components['schemas']['PersonInternV1Person']
				}
			}
			/** @description Personen ble ikke funnet. */
			404: {
				headers: {
					[name: string]: unknown
				}
				content: {
					'*/*': components['schemas']['PersonInternV1Person']
				}
			}
			/** @description Henting av personinformasjon kunne ikke utføres av tekniske årsaker. */
			503: {
				headers: {
					[name: string]: unknown
				}
				content: {
					/**
					 * @example {
					 *       "timestamp": "2023-09-12T10:37:47.056+00:00",
					 *       "status": 503,
					 *       "error": "Service Unavailable",
					 *       "message": "En feil inntraff",
					 *       "path": "/api/ressurs"
					 *     }
					 */
					'*/*': unknown
				}
			}
		}
	}
	sistePensjonsgivendeInntekt: {
		parameters: {
			query?: never
			header?: never
			path?: never
			cookie?: never
		}
		requestBody?: never
		responses: {
			/** @description Henting av inntekt utført. */
			200: {
				headers: {
					[name: string]: unknown
				}
				content: {
					'*/*': components['schemas']['InntektDto']
				}
			}
			/** @description Henting av inntekt kunne ikke utføres av tekniske årsaker */
			503: {
				headers: {
					[name: string]: unknown
				}
				content: {
					/**
					 * @example {
					 *       "timestamp": "2023-09-12T10:37:47.056+00:00",
					 *       "status": 503,
					 *       "error": "Service Unavailable",
					 *       "message": "En feil inntraff",
					 *       "path": "/api/ressurs"
					 *     }
					 */
					'*/*': unknown
				}
			}
		}
	}
	isEnabled: {
		parameters: {
			query?: never
			header?: never
			path: {
				name: string
			}
			cookie?: never
		}
		requestBody?: never
		responses: {
			/** @description Sjekking av funksjonsbryter-status */
			200: {
				headers: {
					[name: string]: unknown
				}
				content: {
					'*/*': components['schemas']['EnablementDto']
				}
			}
			/** @description Sjekking av funksjonsbryter-status kunne ikke utføres av tekniske årsaker */
			503: {
				headers: {
					[name: string]: unknown
				}
				content: {
					/**
					 * @example {
					 *       "timestamp": "2023-09-12T10:37:47.056+00:00",
					 *       "status": 503,
					 *       "error": "Service Unavailable",
					 *       "message": "En feil inntraff",
					 *       "path": "/api/ressurs"
					 *     }
					 */
					'*/*': unknown
				}
			}
		}
	}
}
