apiVersion: nais.io/v1alpha1
kind: Application
metadata:
  name: pensjonskalkulator-frontend-ekstern
  namespace: pensjonskalkulator
  labels:
    team: pensjonskalkulator
  annotations:
    nais.io/run-as-user: '101' # nginx
spec: # TODO legg til ingress
  image: '{{ image }}'
  port: 8080
  replicas:
    min: 2
    max: 4
  liveness:
    path: /internal/health/liveness
    initialDelay: 20
    periodSeconds: 20
    failureThreshold: 5
    timeout: 1
  readiness:
    path: /internal/health/readiness
    initialDelay: 20
    periodSeconds: 20
    failureThreshold: 5
    timeout: 1
  frontend:
    generatedConfig:
      mountPath: /app/src/nais.js
  prometheus:
    enabled: true
    path: /metrics
  observability:
    autoInstrumentation:
      enabled: true
      runtime: nodejs
  gcp:
    buckets:
      - name: pkf
        retentionPeriodDays: 30
        lifecycleCondition:
          age: 7
          createdBefore: 2020-01-01
          numNewerVersions: 2
          withState: ANY
  tokenx:
    enabled: true
  accessPolicy: # TODO legg til Idporten
    outbound:
      rules:
        - application: pensjonskalkulator-backend
      external:
        - host: www.nav.no
        - host: pensjonskalkulator-unleash-api.nav.cloud.nais.io
  env:
    - name: 'PENSJONSKALKULATOR_BACKEND'
      value: 'http://pensjonskalkulator-backend'
    - name: 'TOKEN_X_OBO_AUDIENCE'
      value: 'prod-gcp:pensjonskalkulator:pensjonskalkulator-backend'
    - name: 'DETALJERT_KALKULATOR_URL'
      value: 'https://www.nav.no/pselv/simulering.jsf?simpleMode=true'
  envFrom:
    - secret: pensjonskalkulator-frontend-unleash-api-token
